version: '2'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./database:/database
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/database
  odoo:
    image: odoo
    build: ./odoo-docker/9.0/
    container_name: odoo
    ports:
      - "0.0.0.0:80:8069"
    links:
      - db:db
    depends_on:
      - db
    tty: true
    volumes:
      - ./odoo_filestore:/var/lib/odoo
    environment:
      - PGHOST=db
      - PGUSER=odoo
      - PGPASSWORD=odoo
